# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tweetembed < Formula
  desc "Turn tweets from a Twitter archive into standalone embeddable HTML"
  homepage "https://github.com/duggan/tweetembed"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duggan/tweetembed/releases/download/v0.2.1/tweetembed_0.2.1_darwin_amd64.tar.gz"
      sha256 "e15dd8e66531ea1f37abb049232cc10e828d8014a2325ced3418b85a96addc2a"

      define_method(:install) do
        bin.install "tweetembed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duggan/tweetembed/releases/download/v0.2.1/tweetembed_0.2.1_darwin_arm64.tar.gz"
      sha256 "c6d4ca74f187f7ba4f4ff07a91868f808d957ba684685cf5003d7c67c1ded6c7"

      define_method(:install) do
        bin.install "tweetembed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/tweetembed/releases/download/v0.2.1/tweetembed_0.2.1_linux_amd64.tar.gz"
      sha256 "544612f52f5595c739cb6fef977234ff15edf9e1c610d3c513ebe63607e8b432"
      define_method(:install) do
        bin.install "tweetembed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/tweetembed/releases/download/v0.2.1/tweetembed_0.2.1_linux_arm64.tar.gz"
      sha256 "d0a53b28d40696a19bedac8c43bd226b922a3748c57c85c0dc4bfbb072658043"
      define_method(:install) do
        bin.install "tweetembed"
      end
    end
  end
end
