# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tweetembed < Formula
  desc "Turn tweets from a Twitter archive into standalone embeddable HTML"
  homepage "https://github.com/duggan/tweetembed"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duggan/tweetembed/releases/download/v0.2.0/tweetembed_0.2.0_darwin_amd64.tar.gz"
      sha256 "986ba9185737c8bcfb0f5508bb3dbd4cf2ec736248f0b093970111b41ffcaea5"

      define_method(:install) do
        bin.install "tweetembed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duggan/tweetembed/releases/download/v0.2.0/tweetembed_0.2.0_darwin_arm64.tar.gz"
      sha256 "78afacb72363ef31c25ae3d031467ff8efdbe345dcd73652d38c07f090336a90"

      define_method(:install) do
        bin.install "tweetembed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/tweetembed/releases/download/v0.2.0/tweetembed_0.2.0_linux_amd64.tar.gz"
      sha256 "f8ca181d3d2768c8514f8a42f068a7aec931896948d0d1e3943246523efea453"
      define_method(:install) do
        bin.install "tweetembed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/tweetembed/releases/download/v0.2.0/tweetembed_0.2.0_linux_arm64.tar.gz"
      sha256 "8766e3a911c6f88376786500e78b493257b8c9f9e566b6ae796210229e4f8c8c"
      define_method(:install) do
        bin.install "tweetembed"
      end
    end
  end
end
