# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tweetembed < Formula
  desc "Turn tweets from a Twitter archive into standalone embeddable HTML"
  homepage "https://github.com/duggan/tweetembed"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duggan/tweetembed/releases/download/v0.1.0/tweetembed_0.1.0_darwin_amd64.tar.gz"
      sha256 "f559351131088f77fbd5774bdf48e33d49b8723434d7072b3f4889a64841df59"

      define_method(:install) do
        bin.install "tweetembed"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duggan/tweetembed/releases/download/v0.1.0/tweetembed_0.1.0_darwin_arm64.tar.gz"
      sha256 "4531db1d718333aef769d336b1a4f2227d9e04f5b3701200cdb3c114c7257df4"

      define_method(:install) do
        bin.install "tweetembed"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/tweetembed/releases/download/v0.1.0/tweetembed_0.1.0_linux_amd64.tar.gz"
      sha256 "20c5513f12bca7e58f94c6257b6413b52cd67ae2694bea307cd48ab270ceef43"
      define_method(:install) do
        bin.install "tweetembed"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/tweetembed/releases/download/v0.1.0/tweetembed_0.1.0_linux_arm64.tar.gz"
      sha256 "c3d035a223df4a2fd41075d49590a7a62e7a45589cec402f14eb12bdab04e9c8"
      define_method(:install) do
        bin.install "tweetembed"
      end
    end
  end
end
