# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vhs < Formula
  desc "A tool for recording terminal GIFs with configurable video quality"
  homepage "https://github.com/duggan/vhs"
  version "0.11.0-videoopts"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duggan/vhs/releases/download/v0.11.0-videoopts/vhs_0.11.0-videoopts_darwin_amd64.tar.gz"
      sha256 "044bc6596425cf96865951f2cc2435aa41636ea2e65ba96303e7b0d5ebd12aa4"

      define_method(:install) do
        bin.install "vhs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duggan/vhs/releases/download/v0.11.0-videoopts/vhs_0.11.0-videoopts_darwin_arm64.tar.gz"
      sha256 "859eb69947dc40e6adb6d070006040a09d4ff4e7044eeec85c7bf09932439ed4"

      define_method(:install) do
        bin.install "vhs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/vhs/releases/download/v0.11.0-videoopts/vhs_0.11.0-videoopts_linux_amd64.tar.gz"
      sha256 "7a32e6684b8bc32b9d6029ffb3275b901325592319b158b38ff439ead5884fba"
      define_method(:install) do
        bin.install "vhs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/vhs/releases/download/v0.11.0-videoopts/vhs_0.11.0-videoopts_linux_arm64.tar.gz"
      sha256 "94266475dd3fdbf57327b163c3dfc3af53a4e154455111e08db817380170ec5b"
      define_method(:install) do
        bin.install "vhs"
      end
    end
  end
end
