# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vhs < Formula
  desc "A tool for recording terminal GIFs with configurable video quality"
  homepage "https://github.com/duggan/vhs"
  version "0.11.0-videoopts"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/duggan/vhs/releases/download/v0.11.0-videoopts/vhs_0.11.0-videoopts_darwin_amd64.tar.gz"
      sha256 "9083dc8149844d4bb964173cb3da48bd1e43fba76c7b2826e2cac356ed68c2ab"

      define_method(:install) do
        bin.install "vhs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/duggan/vhs/releases/download/v0.11.0-videoopts/vhs_0.11.0-videoopts_darwin_arm64.tar.gz"
      sha256 "274d2eb5c3d8c99e3e25056c41ab3f2af2c677849f07ac1150c0fc103596efe6"

      define_method(:install) do
        bin.install "vhs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/vhs/releases/download/v0.11.0-videoopts/vhs_0.11.0-videoopts_linux_amd64.tar.gz"
      sha256 "ceb75d2e35cac8c999657484a7603cfb699b26f4a591e37778327e7592a9c2a3"
      define_method(:install) do
        bin.install "vhs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/duggan/vhs/releases/download/v0.11.0-videoopts/vhs_0.11.0-videoopts_linux_arm64.tar.gz"
      sha256 "063e28eb682839572452413400d6046dce865ae46701e131edec3fb9d299fd66"
      define_method(:install) do
        bin.install "vhs"
      end
    end
  end
end
